import Link from "next/link"
import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
      <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header>
        <nav className= "h-[80px] flex justify-center items-center gap-8 text-3xl bg-amber-200">
        <Link href="/">Home</Link><br />
        <Link href="/about">About</Link><br />
        <Link href="/contact">Contact</Link><br />
        </nav>
        </header>
        
        <main className="bg-purple-100 flex-grow p-4 flex justify-center items-center">
          {children}
        </main>

        <footer className=" h-[60px] bg-amber-200 flex justify-center items-center">&copy; 2025 Dexter website</footer>
      </body>
    </html>
  )
}
